{{- if .Values.bf_hpa.mem_enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: epi-bf-hpa-mem
  namespace: epi
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: epi-bf
  minReplicas: {{ .Values.bf_hpa.minReplicas }}
  maxReplicas: {{ .Values.bf_hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.bf_hpa.mem_averageUtilization }}
{{- end }}